[package]
name = "index_camera_passthrough"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
ash = "0.33.3"
vulkano = "0.26.0"
image = "0.23.14"
openvr_sys = { path = "openvr_sys" }
ctrlc = "3.2.1"
log = "0.4.14"
env_logger = "0.9.0"


[features]
